name: scrape

on:
  schedule:
    - cron:  '5 * * * *' # Each day At 11:05 Ref https://crontab.guru/examples.html
  workflow_dispatch:

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      #----------------------------------------------
      #       check-out repo and set-up python     
      #----------------------------------------------
      - name: Check out repository
        uses: actions/checkout@v2
      - name: Set up python 
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      #----------------------------------------------
      #  -----  install python req  -----      
      #----------------------------------------------
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: '3.9'
          cache: 'pip'
      - run: pip install -r requirements.txt
      #----------------------------------------------
      #  -----  decrypt  -----      
      #----------------------------------------------
      - name: Decrypt large secret
        run: ./.github/scripts/decrypt_secret.sh
        env:
          LARGE_SECRET_PASSPHRASE: ${{ secrets.LARGE_SECRET_PASSPHRASE }}
      # This command is just an example to show your secret being printed
      # Ensure you remove any print statements of your secrets. GitHub does
      # not hide secrets that use this workaround.
      #----------------------------------------------
      # run scrape
      #----------------------------------------------       
      - name: Scrape
        run: |
          python scrape.py
          python to_spreadsheet.py


      #----------------------------------------------
      # publish to github
      #----------------------------------------------

      - uses: mikeal/publish-to-github-action@master
        env:
          BRANCH_NAME: 'main'
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
