name: test_env_secrets

on:
  workflow_dispatch:

jobs:
  build:
  
    name: Build
    runs-on: ubuntu-latest
    steps:
      #----------------------------------------------
      #       check-out repo and set-up python     
      #----------------------------------------------
      - name: Check out repository
        uses: actions/checkout@v2
      - name: Set up python 
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      #----------------------------------------------
      #  -----  install python req  -----      
      #----------------------------------------------
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: '3.9'
          cache: 'pip'
      - run: pip install -r requirements.txt
      #----------------------------------------------
      #  -----  decrypt  -----      
      #----------------------------------------------
      - uses: actions/checkout@v2
      - name: Decrypt large secret
        run: ./.github/scripts/decrypt_secret.sh
        env:
          LARGE_SECRET_PASSPHRASE: ${{ secrets.LARGE_SECRET_PASSPHRASE }}
      # This command is just an example to show your secret being printed
      # Ensure you remove any print statements of your secrets. GitHub does
      # not hide secrets that use this workaround.
      - name: Test printing your secret (Remove this step in production)
        run: cat $HOME/secrets/config.json
      #----------------------------------------------
      # run python
      #----------------------------------------------       
      - name: Scrape
        env:
          SERVICE_ACC: ${{ secrets.SERVICE_ACC }} 
        run: |
          python -c 'import os;print(os.environ)'
          python to_spreadsheet.py
